### PR TITLE
added Jackson.txt

### PR DESCRIPTION
**Pull request by jmduhon**

### CODE REVIEW

**Comment by kedeger** [comment]
💯

**Comment by ChrisKenyon79** [comment]
MORE EXCELLENT CODE

**Comment by ChrisKenyon79** [comment]
MORE EXCELLENT CODE

**Comment by zmcdaniel** [comment]
```
   _~
_~ )_)_~
)_))_))_)
_!__!__!_
\______t/
```

  ~~~~~~~~~~~~~ <--- it's a boat

**Comment by ChrisKenyon79** [comment]
MORE EXCELLENT CODE

**Comment by ChrisKenyon79** [comment]
MORE EXCELLENT CODE

**Pull request merged**
